### ISSUE TITLE
Gerrit  question

### ISSUE THREAD

**Issue by autopy** [jruesga/rview#28]
Hi, I would like to ask the following error “Something went wrong  RETRY”  What's the cause?   Is the project authority, or gerrit config？

Look forward to your reply.

**Comment by jruesga** [comment]
Normally, it could be a server error. Can you obtain a logcat of the device after fetch the changes and got the error? It's a public gerrit instance i can connect to? Authenticated or guess user?

**Comment by autopy** [comment]
Thank you very much for your letter！ click open project 。Error as shown
![20170425145230](https://cloud.githubusercontent.com/assets/27993831/25412274/30864e84-2a54-11e7-9553-6caeb21129df.png)

Sorry, My Gerrit is private!   LDAP Authenticated 。

I think I have a problem with the configuration。

[auth]
       type = LDAP
       gitBasicAuth = true

**Comment by jruesga** [comment]
According to your comments and screenshot, doesn't seems to a configuration problem to me, but a bad request or an error on request treatment.
From your screenshot, you created an account (so you got authenticated and also the app did some basic checks about the gerrit instance), so all seems ok. Also you got into change listing.

is it the problem related to only one change or with every change you try to access to?

As I said before, to determine the problem, I need a logcat from the device after you get the error. This will give the possibility to analyze which request failed, its http status code and stacktraces of the failure.

To get a logcat follow these steps https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/

**Comment by autopy** [comment]
04-27 08:26:18.281 2555-2591/? I/Gerrit: <-- 400 Bad Request http://xxxxxxx/a/changes/2280?o=DETAILED_ACCOUNTS&o=DETAILED_LABELS&o=ALL_REVISIONS&o=ALL_FILES&o=ALL_COMMITS&o=MESSAGES&o=REVIEWED&o=CHANGE_ACTIONS&o=CHECK&o=WEB_LINKS (81ms, 47-byte body)
04-27 08:26:18.335 1714-1803/? I/Timeline: Timeline: App_transition_ready time:14643061
04-27 08:26:18.330 3539-3539/? W/Binder_F: type=1400 audit(0.0:826829): avc: denied { ioctl } for path="socket:[829680]" dev="sockfs" ino=829680 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
04-27 08:26:18.330 3539-3539/? W/Binder_F: type=1400 audit(0.0:826830): avc: denied { ioctl } for path="socket:[829680]" dev="sockfs" ino=829680 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
04-27 08:26:18.339 1714-1803/? I/ActivityManager: Displayed com.ruesga.rview/.ChangeDetailsActivity: +359ms
04-27 08:26:18.339 2906-2906/? V/PhoneStatusBarPolicy: updateManagedProfile mManagedProfileFocused: false mKeyguardVisible: false mCurrentUserId:0 mCurrentProfileId:0 mSecondSpaceStatusIconVisible: true showIcon:false
04-27 08:26:18.354 2555-2555/? E/ChangeDetailsFragment: Invalid request
                                                        java.lang.RuntimeException: com.f.b.a.a.c: HTTP 400 Bad Request
                                                            at a.b.e.h.b.a(SourceFile:45)
                                                            at a.b.e.d.b.b(SourceFile:79)
                                                            at a.b.e.c(SourceFile:4536)
                                                            at com.ruesga.rview.gerrit.d.c(SourceFile:646)
                                                            at com.ruesga.rview.gerrit.g.call(Unknown Source)
                                                            at b.a.a.a.b.call(SourceFile:37)
                                                            at b.a.a.a.d.a(SourceFile:46)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at a.b.e.c(SourceFile:4535)
                                                            at com.ruesga.rview.gerrit.d.b(SourceFile:196)
                                                            at com.ruesga.rview.gerrit.k.call(Unknown Source)
                                                            at b.a.a.a.b.call(SourceFile:37)
                                                            at b.a.a.a.d.a(SourceFile:46)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at a.b.e.c(SourceFile:4535)
                                                            at com.ruesga.rview.d.j.b(SourceFile:1168)
                                                            at com.ruesga.rview.d.n.call(Unknown Source)
                                                            at b.a.a.a.b.call(SourceFile:37)
                                                            at b.a.a.a.d.a(SourceFile:46)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at a.b.e.e.b.m$a.a(SourceFile:110)
                                                            at a.b.e.e.b.m.a(SourceFile:72)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at a.b.e.e.b.l$1.run(SourceFile:39)
                                                            at a.b.h$1.run(SourceFile:134)
                                                            at a.b.e.g.f.run(SourceFile:59)
                                                            at a.b.e.g.f.call(SourceFile:51)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                            at java.lang.Thread.run(Thread.java:818)
                                                         Caused by: com.f.b.a.a.c: HTTP 400 Bad Request
                                                            at com.f.b.a.a.a$a.a(SourceFile:54)
                                                            at com.f.b.a.a.a$a.a_(SourceFile:37)
                                                            at com.f.b.a.a.b.a(SourceFile:43)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at com.f.b.a.a.a.a(SourceFile:34)
                                                            at a.b.e.b(SourceFile:10514)
                                                            at a.b.e.c(SourceFile:4535)
                                                            at com.ruesga.rview.gerrit.d.c(SourceFile:646) 
                                                            at com.ruesga.rview.gerrit.g.call(Unknown Source) 
                                                            at b.a.a.a.b.call(SourceFile:37) 
                                                            at b.a.a.a.d.a(SourceFile:46) 
                                                            at a.b.e.b(SourceFile:10514) 
                                                            at a.b.e.c(SourceFile:4535) 
                                                            at com.ruesga.rview.gerrit.d.b(SourceFile:196) 
                                                            at com.ruesga.rview.gerrit.k.call(Unknown Source) 
                                                            at b.a.a.a.b.call(SourceFile:37) 
                                                            at b.a.a.a.d.a(SourceFile:46) 
                                                            at a.b.e.b(SourceFile:10514) 
                                                            at a.b.e.c(SourceFile:4535) 
                                                            at com.ruesga.rview.d.j.b(SourceFile:1168) 
                                                            at com.ruesga.rview.d.n.call(Unknown Source) 
                                                            at b.a.a.a.b.call(SourceFile:37) 
                                                            at b.a.a.a.d.a(SourceFile:46) 
                                                            at a.b.e.b(SourceFile:10514) 
                                                            at a.b.e.e.b.m$a.a(SourceFile:110) 
                                                            at a.b.e.e.b.m.a(SourceFile:72) 
                                                            at a.b.e.b(SourceFile:10514) 
                                                            at a.b.e.e.b.l$1.run(SourceFile:39) 
                                                            at a.b.h$1.run(SourceFile:134) 
                                                            at a.b.e.g.f.run(SourceFile:59) 
                                                            at a.b.e.g.f.call(SourceFile:51) 
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by jruesga** [comment]
@autopy which is the version of the gerrit instance? The server is responding that the request is not valid, so one or various of the options passed to obtain detailed information is not accepted by your gerrit instance.

**Comment by autopy** [comment]
Hello, I found my version is 2.9， Would like to ask, there is no 2.9?

**Comment by jruesga** [comment]
@autopy Rview only supports 2.11 and high. Version 2.9 doesn't many of the features implemented in Rview.
