### ISSUE TITLE
ChangeDetailsFragment not loading commits from Fuchsia gerrit

### ISSUE THREAD

**Issue by jruesga** [jruesga/rview#71]
E/ChangeDetailsFragment: Request error
    java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 9
    \{change}
             ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:1340)
        at java.util.regex.Pattern.<init>(Pattern.java:1324)
        at java.util.regex.Pattern.compile(Pattern.java:946)
        at java.lang.String.replaceFirst(String.java:2171)
        at com.ruesga.rview.misc.i.b(SourceFile:72)
        at com.ruesga.rview.misc.i.a(SourceFile:60)
        at com.ruesga.rview.fragments.ChangeDetailsFragment.a(SourceFile:2076)
        at com.ruesga.rview.fragments.bf.call(Unknown Source:10)
        at b.a.a.a.b.call(SourceFile:37)
        at b.a.a.a.d.b(SourceFile:46)
        at a.b.e.a(SourceFile:12005)
        at a.b.e.e.b.m$a.a(SourceFile:110)
        at a.b.e.e.b.m.b(SourceFile:72)
        at a.b.e.a(SourceFile:12005)
        at a.b.e.e.b.i.a(SourceFile:96)
        at a.b.e.e.b.e.b(SourceFile:51)
        at a.b.e.a(SourceFile:12005)
        at a.b.e.e.b.l$b.run(SourceFile:96)
        at a.b.h$a.run(SourceFile:571)
        at a.b.e.g.i.run(SourceFile:66)
        at a.b.e.g.i.call(SourceFile:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jruesga** [comment]
Fixed in 5f00149b32664c4928148545ab06973dd6a08a2f
